### ISSUE TITLE
Waybar tooltips not placed correctly

### ISSUE THREAD

**Issue by wmww** [MirServer/egmde-snap#50]
Incorrectly placed popups was a known Waybar bug that was fixed [here](https://github.com/Alexays/Waybar/pull/441) by using gtk-layer-shell. It appears that didn't make it into 20.04, as the version there does not depend on gtk-layer-shell.

If it was going to be fixed, the most obvious way would be to build a newer Waybar from source in the snap. It might also be required to build gtk-layer-shell, if the newer Waybar requires a newer version than is in 20.04 (if so, that can be copied from [here](https://github.com/wmww/mate-wayland-snap/blob/e9e98c0486110f379a06ec7431e8a2f194ee85a1/snap/snapcraft.yaml#L63)).

**Comment by AlanGriffiths** [comment]
Maybe a snapped Waybar? (I guess the first thing is to try the version from the 21.04 archive.)

**Comment by AlanGriffiths** [comment]
> Maybe a snapped Waybar? (I guess the first thing is to try the version from the 21.04 archive.)

Confirmed: Using the waybar installed from the 21.04 archive the tooltips are better placed.

```plain
sudo apt install waybar fonts-font-awesome
sed --in-place "s#/snap/egmde/current/bin/waybar.launcher#waybar#" ~/.config/egmde.config
```
